language: generic

cache:
  apt: true

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env: COMPILER=g++-5

before_install:
- mkdir -p ~/.cmake
- export PATH=$HOME/.cmake/cmake-3.6.2-Linux-x86_64/bin:$PATH
- travis_retry curl -s https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz | tar -xz -C ~/.cmake

before_script:
- cmake --version
- ./deps.sh

script:
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make && make test
