os:
- linux

matrix:
  include:
  - os: osx
    osx_image: xcode7.3

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - gcc-5
    - g++-5
    - clang-3.8

language: cpp
compiler:
- gcc
- clang

notifications:
  email:
    on_success: never
    on_failure: always

before_install: ./travis.sh

install:
- if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
- cmake --version

before_script: ./deps.sh

script: mkdir -p build && cd build && cmake .. && make && make test
